[project]
name = "travel-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sunub", email = "bsc5672@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.1",
    "torch>=2.14.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
travel-planner = "travel_planner:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "backend"
