[project]
name = "travel-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sunub", email = "bsc5672@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.0",
    "bitsandbytes>=0.46",
    "datasets>=3.0",
    "peft>=0.14",
    "psycopg[binary]>=3.2",
    "python-dotenv>=1.0",
    "requests>=2.34.2",
    "sentencepiece>=0.2",
    "torch>=2.14.0",
    "transformers>=4.51",
    "trl>=0.16",
    "wandb>=0.19",
]

[project.scripts]
travel-planner = "travel_planner:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
